# Generated by Django 3.2.8 on 2021-12-07 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0002_test2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test2',
            name='num',
            field=models.PositiveIntegerField(default=1, verbose_name='номер'),
        ),
        migrations.AlterField(
            model_name='test2',
            name='price',
            field=models.PositiveIntegerField(default=1, verbose_name='цена'),
        ),
    ]
