# Generated by Django 3.2.8 on 2021-12-03 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('w2', '0002_person_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
